<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Patient;
use Carbon\Carbon;

class PatientSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $patients = [
            [
                'mr_number' => 'MR-001',
                'patient_type' => 'General',
                'registration_date' => Carbon::now(),
                'name' => 'Ahmed Ali',
                'marital_status' => 'Single',
                'date_of_birth' => Carbon::parse('1995-05-15'),
                'relation_type' => 'Father',
                'guardian_name' => 'Ali Khan',
                'guardian_cnic' => '42101-1234567-1',
                'age' => 29,
                'is_welfare' => false,
                'weight' => 70.5,
                'gender' => 'Male',
                'email' => 'ahmed.ali@example.com',
                'cnic' => '42101-7654321-1',
                'address' => 'House 123, Sector 5, Karachi',
                'mobile_number' => '0300-1234567',
            ],
            [
                'mr_number' => 'MR-002',
                'patient_type' => 'General',
                'registration_date' => Carbon::now(),
                'name' => 'Sara Fatima',
                'marital_status' => 'Married',
                'date_of_birth' => Carbon::parse('1990-10-20'),
                'relation_type' => 'Husband',
                'guardian_name' => 'Muhammad Bilal',
                'guardian_cnic' => '42101-2345678-2',
                'age' => 33,
                'is_welfare' => true,
                'weight' => 60.0,
                'gender' => 'Female',
                'email' => 'sara.fatima@example.com',
                'cnic' => '42101-8765432-2',
                'address' => 'Flat A-4, Gulshan-e-Iqbal, Karachi',
                'mobile_number' => '0311-2345678',
            ],
            [
                'mr_number' => 'MR-003',
                'patient_type' => 'Staff',
                'registration_date' => Carbon::now(),
                'name' => 'Zubair Ahmed',
                'marital_status' => 'Single',
                'date_of_birth' => Carbon::parse('1985-02-10'),
                'relation_type' => 'Father',
                'guardian_name' => 'Ahmed Shah',
                'guardian_cnic' => '42101-3456789-3',
                'age' => 39,
                'is_welfare' => false,
                'weight' => 80.2,
                'gender' => 'Male',
                'email' => 'zubair.ahmed@example.com',
                'cnic' => '42101-9876543-3',
                'address' => 'North Nazimabad, Karachi',
                'mobile_number' => '0322-3456789',
            ],
            [
                'mr_number' => 'MR-004',
                'patient_type' => 'General',
                'registration_date' => Carbon::now(),
                'name' => 'Ayesha Khan',
                'marital_status' => 'Single',
                'date_of_birth' => Carbon::parse('2000-12-25'),
                'relation_type' => 'Father',
                'guardian_name' => 'Khan Mohammad',
                'guardian_cnic' => '42101-4567890-4',
                'age' => 23,
                'is_welfare' => false,
                'weight' => 55.5,
                'gender' => 'Female',
                'email' => 'ayesha.khan@example.com',
                'cnic' => '42101-0987654-4',
                'address' => 'DHA Phase 6, Karachi',
                'mobile_number' => '0333-4567890',
            ],
            [
                'mr_number' => 'MR-005',
                'patient_type' => 'Welfare',
                'registration_date' => Carbon::now(),
                'name' => 'Usman Raza',
                'marital_status' => 'Married',
                'date_of_birth' => Carbon::parse('1975-07-05'),
                'relation_type' => 'Father',
                'guardian_name' => 'Raza Hussain',
                'guardian_cnic' => '42101-5678901-5',
                'age' => 48,
                'is_welfare' => true,
                'weight' => 75.0,
                'gender' => 'Male',
                'email' => 'usman.raza@example.com',
                'cnic' => '42101-1098765-5',
                'address' => 'Orangi Town, Karachi',
                'mobile_number' => '0344-5678901',
            ],
            [
                'mr_number' => 'MR-006',
                'patient_type' => 'General',
                'registration_date' => Carbon::now(),
                'name' => 'Hina Malik',
                'marital_status' => 'Married',
                'date_of_birth' => Carbon::parse('1992-03-12'),
                'relation_type' => 'Husband',
                'guardian_name' => 'Malik Tahir',
                'guardian_cnic' => '42101-6789012-6',
                'age' => 32,
                'is_welfare' => false,
                'weight' => 62.8,
                'gender' => 'Female',
                'email' => 'hina.malik@example.com',
                'cnic' => '42101-2109876-6',
                'address' => 'Clifton, Karachi',
                'mobile_number' => '0355-6789012',
            ],
            [
                'mr_number' => 'MR-007',
                'patient_type' => 'General',
                'registration_date' => Carbon::now(),
                'name' => 'Bilal Sheikh',
                'marital_status' => 'Single',
                'date_of_birth' => Carbon::parse('1988-08-30'),
                'relation_type' => 'Father',
                'guardian_name' => 'Sheikh Rashid',
                'guardian_cnic' => '42101-7890123-7',
                'age' => 35,
                'is_welfare' => false,
                'weight' => 85.5,
                'gender' => 'Male',
                'email' => 'bilal.sheikh@example.com',
                'cnic' => '42101-3210987-7',
                'address' => 'Saddar, Karachi',
                'mobile_number' => '0366-7890123',
            ],
            [
                'mr_number' => 'MR-008',
                'patient_type' => 'General',
                'registration_date' => Carbon::now(),
                'name' => 'Sana Javed',
                'marital_status' => 'Single',
                'date_of_birth' => Carbon::parse('1998-01-18'),
                'relation_type' => 'Father',
                'guardian_name' => 'Javed Iqbal',
                'guardian_cnic' => '42101-8901234-8',
                'age' => 26,
                'is_welfare' => true,
                'weight' => 58.0,
                'gender' => 'Female',
                'email' => 'sana.javed@example.com',
                'cnic' => '42101-4321098-8',
                'address' => 'Bahadurabad, Karachi',
                'mobile_number' => '0301-8901234',
            ],
            [
                'mr_number' => 'MR-009',
                'patient_type' => 'General',
                'registration_date' => Carbon::now(),
                'name' => 'Hamza Saeed',
                'marital_status' => 'Single',
                'date_of_birth' => Carbon::parse('2005-06-22'),
                'relation_type' => 'Father',
                'guardian_name' => 'Saeed Anwar',
                'guardian_cnic' => '42101-9012345-9',
                'age' => 18,
                'is_welfare' => false,
                'weight' => 68.0,
                'gender' => 'Male',
                'email' => 'hamza.saeed@example.com',
                'cnic' => '42101-5432109-9',
                'address' => 'Model Colony, Karachi',
                'mobile_number' => '0312-9012345',
            ],
            [
                'mr_number' => 'MR-010',
                'patient_type' => 'General',
                'registration_date' => Carbon::now(),
                'name' => 'Nida Pervez',
                'marital_status' => 'Married',
                'date_of_birth' => Carbon::parse('1982-11-11'),
                'relation_type' => 'Husband',
                'guardian_name' => 'Pervez Musharraf',
                'guardian_cnic' => '42101-0123456-0',
                'age' => 41,
                'is_welfare' => false,
                'weight' => 65.2,
                'gender' => 'Female',
                'email' => 'nida.pervez@example.com',
                'cnic' => '42101-6543210-0',
                'address' => 'Korangi, Karachi',
                'mobile_number' => '0323-0123456',
            ],
        ];

        foreach ($patients as $patient) {
            Patient::updateOrCreate(['mr_number' => $patient['mr_number']], $patient);
        }
    }
}
